-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Parser.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Parser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Parser.Abs.Ident -> Result
transIdent x = case x of
  Parser.Abs.Ident string -> failure x

transProgram :: Show a => Parser.Abs.Program' a -> Result
transProgram x = case x of
  Parser.Abs.Program _ topdefs -> failure x

transTopDef :: Show a => Parser.Abs.TopDef' a -> Result
transTopDef x = case x of
  Parser.Abs.FnDef _ type_ ident args block -> failure x
  Parser.Abs.VarDef _ type_ items -> failure x

transArg :: Show a => Parser.Abs.Arg' a -> Result
transArg x = case x of
  Parser.Abs.ArgVal _ type_ ident -> failure x
  Parser.Abs.ArgRef _ type_ ident -> failure x

transBlock :: Show a => Parser.Abs.Block' a -> Result
transBlock x = case x of
  Parser.Abs.Block _ stmts -> failure x

transStmt :: Show a => Parser.Abs.Stmt' a -> Result
transStmt x = case x of
  Parser.Abs.Empty _ -> failure x
  Parser.Abs.BStmt _ block -> failure x
  Parser.Abs.FnDecl _ type_ ident args block -> failure x
  Parser.Abs.VarDecl _ type_ items -> failure x
  Parser.Abs.Ass _ ident expr -> failure x
  Parser.Abs.Incr _ ident -> failure x
  Parser.Abs.Decr _ ident -> failure x
  Parser.Abs.Ret _ expr -> failure x
  Parser.Abs.VRet _ -> failure x
  Parser.Abs.Cond _ expr block -> failure x
  Parser.Abs.CondElse _ expr block1 block2 -> failure x
  Parser.Abs.While _ expr block -> failure x
  Parser.Abs.SExp _ expr -> failure x

transItem :: Show a => Parser.Abs.Item' a -> Result
transItem x = case x of
  Parser.Abs.NoInit _ ident -> failure x
  Parser.Abs.Init _ ident expr -> failure x

transType :: Show a => Parser.Abs.Type' a -> Result
transType x = case x of
  Parser.Abs.Int _ -> failure x
  Parser.Abs.Str _ -> failure x
  Parser.Abs.Bool _ -> failure x
  Parser.Abs.Void _ -> failure x

transExpr :: Show a => Parser.Abs.Expr' a -> Result
transExpr x = case x of
  Parser.Abs.EVar _ ident -> failure x
  Parser.Abs.ELitInt _ integer -> failure x
  Parser.Abs.ELitTrue _ -> failure x
  Parser.Abs.ELitFalse _ -> failure x
  Parser.Abs.EApp _ ident exprs -> failure x
  Parser.Abs.EString _ string -> failure x
  Parser.Abs.Neg _ expr -> failure x
  Parser.Abs.Not _ expr -> failure x
  Parser.Abs.EMul _ expr1 mulop expr2 -> failure x
  Parser.Abs.EAdd _ expr1 addop expr2 -> failure x
  Parser.Abs.ERel _ expr1 relop expr2 -> failure x
  Parser.Abs.EAnd _ expr1 expr2 -> failure x
  Parser.Abs.EOr _ expr1 expr2 -> failure x

transAddOp :: Show a => Parser.Abs.AddOp' a -> Result
transAddOp x = case x of
  Parser.Abs.Plus _ -> failure x
  Parser.Abs.Minus _ -> failure x

transMulOp :: Show a => Parser.Abs.MulOp' a -> Result
transMulOp x = case x of
  Parser.Abs.Times _ -> failure x
  Parser.Abs.Div _ -> failure x
  Parser.Abs.Mod _ -> failure x

transRelOp :: Show a => Parser.Abs.RelOp' a -> Result
transRelOp x = case x of
  Parser.Abs.LTH _ -> failure x
  Parser.Abs.LE _ -> failure x
  Parser.Abs.GTH _ -> failure x
  Parser.Abs.GE _ -> failure x
  Parser.Abs.EQU _ -> failure x
  Parser.Abs.NE _ -> failure x
